- hosts: all
  tasks:
  - name: setting up repository
    yum_repository:
      name: docker
      description: docker repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no
  - name: installing docker packages
    package:
       name: docker-ce-18.09.1-3.el7.x86_64
       state: present
  - name: installing other packages
    package:
       name: httpd,firefox,python3
       state: present
  - name: installing python for docker
    command: pip3 install docker
  - name: starting services
    service:
       name: httpd
       state: started
  - name: "Creating Folder"
    file:
       path: /webpages
       state: directory
  - name: "Copying the html files"
    copy:
       src:  "/root/web.html"
       dest: "/webpages"
  - name: "Starting docker"  
    service:
       name: docker
       state: started
       enabled: yes
  - name: installing docker images
    docker_image:
       name: httpd
  - name: launching container
    docker_container:
       name: myhttpd
       image: httpd
       state: started
       exposed_ports:
       - "80"
       ports:
       - "8080:80"
       volumes:
       - /webpages:/usr/local/apache2/htdocs/
